// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelrate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupModelRateUpdate is the builder for updating GroupModelRate entities.
type GroupModelRateUpdate struct {
	config
	hooks    []Hook
	mutation *GroupModelRateMutation
}

// Where appends a list predicates to the GroupModelRateUpdate builder.
func (_u *GroupModelRateUpdate) Where(ps ...predicate.GroupModelRate) *GroupModelRateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupModelRateUpdate) SetGroupID(v int64) *GroupModelRateUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupModelRateUpdate) SetNillableGroupID(v *int64) *GroupModelRateUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GroupModelRateUpdate) SetModel(v string) *GroupModelRateUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GroupModelRateUpdate) SetNillableModel(v *string) *GroupModelRateUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *GroupModelRateUpdate) SetRateMultiplier(v float64) *GroupModelRateUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *GroupModelRateUpdate) SetNillableRateMultiplier(v *float64) *GroupModelRateUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *GroupModelRateUpdate) AddRateMultiplier(v float64) *GroupModelRateUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetCardPrice sets the "card_price" field.
func (_u *GroupModelRateUpdate) SetCardPrice(v float64) *GroupModelRateUpdate {
	_u.mutation.ResetCardPrice()
	_u.mutation.SetCardPrice(v)
	return _u
}

// SetNillableCardPrice sets the "card_price" field if the given value is not nil.
func (_u *GroupModelRateUpdate) SetNillableCardPrice(v *float64) *GroupModelRateUpdate {
	if v != nil {
		_u.SetCardPrice(*v)
	}
	return _u
}

// AddCardPrice adds value to the "card_price" field.
func (_u *GroupModelRateUpdate) AddCardPrice(v float64) *GroupModelRateUpdate {
	_u.mutation.AddCardPrice(v)
	return _u
}

// ClearCardPrice clears the value of the "card_price" field.
func (_u *GroupModelRateUpdate) ClearCardPrice() *GroupModelRateUpdate {
	_u.mutation.ClearCardPrice()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupModelRateUpdate) SetUpdatedAt(v time.Time) *GroupModelRateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupModelRateUpdate) SetGroup(v *Group) *GroupModelRateUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupModelRateMutation object of the builder.
func (_u *GroupModelRateUpdate) Mutation() *GroupModelRateMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupModelRateUpdate) ClearGroup() *GroupModelRateUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupModelRateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupModelRateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupModelRateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupModelRateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupModelRateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupmodelrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupModelRateUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := groupmodelrate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GroupModelRate.model": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupModelRate.group"`)
	}
	return nil
}

func (_u *GroupModelRateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmodelrate.Table, groupmodelrate.Columns, sqlgraph.NewFieldSpec(groupmodelrate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(groupmodelrate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(groupmodelrate.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(groupmodelrate.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CardPrice(); ok {
		_spec.SetField(groupmodelrate.FieldCardPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCardPrice(); ok {
		_spec.AddField(groupmodelrate.FieldCardPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CardPriceCleared() {
		_spec.ClearField(groupmodelrate.FieldCardPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmodelrate.GroupTable,
			Columns: []string{groupmodelrate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmodelrate.GroupTable,
			Columns: []string{groupmodelrate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmodelrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupModelRateUpdateOne is the builder for updating a single GroupModelRate entity.
type GroupModelRateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupModelRateMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupModelRateUpdateOne) SetGroupID(v int64) *GroupModelRateUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupModelRateUpdateOne) SetNillableGroupID(v *int64) *GroupModelRateUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GroupModelRateUpdateOne) SetModel(v string) *GroupModelRateUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GroupModelRateUpdateOne) SetNillableModel(v *string) *GroupModelRateUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *GroupModelRateUpdateOne) SetRateMultiplier(v float64) *GroupModelRateUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *GroupModelRateUpdateOne) SetNillableRateMultiplier(v *float64) *GroupModelRateUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *GroupModelRateUpdateOne) AddRateMultiplier(v float64) *GroupModelRateUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetCardPrice sets the "card_price" field.
func (_u *GroupModelRateUpdateOne) SetCardPrice(v float64) *GroupModelRateUpdateOne {
	_u.mutation.ResetCardPrice()
	_u.mutation.SetCardPrice(v)
	return _u
}

// SetNillableCardPrice sets the "card_price" field if the given value is not nil.
func (_u *GroupModelRateUpdateOne) SetNillableCardPrice(v *float64) *GroupModelRateUpdateOne {
	if v != nil {
		_u.SetCardPrice(*v)
	}
	return _u
}

// AddCardPrice adds value to the "card_price" field.
func (_u *GroupModelRateUpdateOne) AddCardPrice(v float64) *GroupModelRateUpdateOne {
	_u.mutation.AddCardPrice(v)
	return _u
}

// ClearCardPrice clears the value of the "card_price" field.
func (_u *GroupModelRateUpdateOne) ClearCardPrice() *GroupModelRateUpdateOne {
	_u.mutation.ClearCardPrice()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupModelRateUpdateOne) SetUpdatedAt(v time.Time) *GroupModelRateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupModelRateUpdateOne) SetGroup(v *Group) *GroupModelRateUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupModelRateMutation object of the builder.
func (_u *GroupModelRateUpdateOne) Mutation() *GroupModelRateMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupModelRateUpdateOne) ClearGroup() *GroupModelRateUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupModelRateUpdate builder.
func (_u *GroupModelRateUpdateOne) Where(ps ...predicate.GroupModelRate) *GroupModelRateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupModelRateUpdateOne) Select(field string, fields ...string) *GroupModelRateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupModelRate entity.
func (_u *GroupModelRateUpdateOne) Save(ctx context.Context) (*GroupModelRate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupModelRateUpdateOne) SaveX(ctx context.Context) *GroupModelRate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupModelRateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupModelRateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupModelRateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupmodelrate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupModelRateUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := groupmodelrate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GroupModelRate.model": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupModelRate.group"`)
	}
	return nil
}

func (_u *GroupModelRateUpdateOne) sqlSave(ctx context.Context) (_node *GroupModelRate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupmodelrate.Table, groupmodelrate.Columns, sqlgraph.NewFieldSpec(groupmodelrate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupModelRate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmodelrate.FieldID)
		for _, f := range fields {
			if !groupmodelrate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupmodelrate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(groupmodelrate.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(groupmodelrate.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(groupmodelrate.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CardPrice(); ok {
		_spec.SetField(groupmodelrate.FieldCardPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCardPrice(); ok {
		_spec.AddField(groupmodelrate.FieldCardPrice, field.TypeFloat64, value)
	}
	if _u.mutation.CardPriceCleared() {
		_spec.ClearField(groupmodelrate.FieldCardPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelrate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmodelrate.GroupTable,
			Columns: []string{groupmodelrate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmodelrate.GroupTable,
			Columns: []string{groupmodelrate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupModelRate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupmodelrate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
