// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupmodelrate"
)

// GroupModelRateCreate is the builder for creating a GroupModelRate entity.
type GroupModelRateCreate struct {
	config
	mutation *GroupModelRateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupModelRateCreate) SetGroupID(v int64) *GroupModelRateCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *GroupModelRateCreate) SetModel(v string) *GroupModelRateCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *GroupModelRateCreate) SetRateMultiplier(v float64) *GroupModelRateCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *GroupModelRateCreate) SetNillableRateMultiplier(v *float64) *GroupModelRateCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupModelRateCreate) SetCreatedAt(v time.Time) *GroupModelRateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupModelRateCreate) SetNillableCreatedAt(v *time.Time) *GroupModelRateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroupModelRateCreate) SetUpdatedAt(v time.Time) *GroupModelRateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroupModelRateCreate) SetNillableUpdatedAt(v *time.Time) *GroupModelRateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupModelRateCreate) SetGroup(v *Group) *GroupModelRateCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupModelRateMutation object of the builder.
func (_c *GroupModelRateCreate) Mutation() *GroupModelRateMutation {
	return _c.mutation
}

// Save creates the GroupModelRate in the database.
func (_c *GroupModelRateCreate) Save(ctx context.Context) (*GroupModelRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupModelRateCreate) SaveX(ctx context.Context) *GroupModelRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupModelRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupModelRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupModelRateCreate) defaults() {
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := groupmodelrate.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupmodelrate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := groupmodelrate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupModelRateCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupModelRate.group_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "GroupModelRate.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := groupmodelrate.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GroupModelRate.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "GroupModelRate.rate_multiplier"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupModelRate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GroupModelRate.updated_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupModelRate.group"`)}
	}
	return nil
}

func (_c *GroupModelRateCreate) sqlSave(ctx context.Context) (*GroupModelRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupModelRateCreate) createSpec() (*GroupModelRate, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupModelRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupmodelrate.Table, sqlgraph.NewFieldSpec(groupmodelrate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(groupmodelrate.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(groupmodelrate.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupmodelrate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(groupmodelrate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupmodelrate.GroupTable,
			Columns: []string{groupmodelrate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupModelRate.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupModelRateUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupModelRateCreate) OnConflict(opts ...sql.ConflictOption) *GroupModelRateUpsertOne {
	_c.conflict = opts
	return &GroupModelRateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupModelRateCreate) OnConflictColumns(columns ...string) *GroupModelRateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupModelRateUpsertOne{
		create: _c,
	}
}

type (
	// GroupModelRateUpsertOne is the builder for "upsert"-ing
	//  one GroupModelRate node.
	GroupModelRateUpsertOne struct {
		create *GroupModelRateCreate
	}

	// GroupModelRateUpsert is the "OnConflict" setter.
	GroupModelRateUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupModelRateUpsert) SetGroupID(v int64) *GroupModelRateUpsert {
	u.Set(groupmodelrate.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRateUpsert) UpdateGroupID() *GroupModelRateUpsert {
	u.SetExcluded(groupmodelrate.FieldGroupID)
	return u
}

// SetModel sets the "model" field.
func (u *GroupModelRateUpsert) SetModel(v string) *GroupModelRateUpsert {
	u.Set(groupmodelrate.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupModelRateUpsert) UpdateModel() *GroupModelRateUpsert {
	u.SetExcluded(groupmodelrate.FieldModel)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *GroupModelRateUpsert) SetRateMultiplier(v float64) *GroupModelRateUpsert {
	u.Set(groupmodelrate.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *GroupModelRateUpsert) UpdateRateMultiplier() *GroupModelRateUpsert {
	u.SetExcluded(groupmodelrate.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *GroupModelRateUpsert) AddRateMultiplier(v float64) *GroupModelRateUpsert {
	u.Add(groupmodelrate.FieldRateMultiplier, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRateUpsert) SetUpdatedAt(v time.Time) *GroupModelRateUpsert {
	u.Set(groupmodelrate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRateUpsert) UpdateUpdatedAt() *GroupModelRateUpsert {
	u.SetExcluded(groupmodelrate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupModelRateUpsertOne) UpdateNewValues() *GroupModelRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupmodelrate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupModelRateUpsertOne) Ignore() *GroupModelRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupModelRateUpsertOne) DoNothing() *GroupModelRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupModelRateCreate.OnConflict
// documentation for more info.
func (u *GroupModelRateUpsertOne) Update(set func(*GroupModelRateUpsert)) *GroupModelRateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupModelRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupModelRateUpsertOne) SetGroupID(v int64) *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRateUpsertOne) UpdateGroupID() *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateGroupID()
	})
}

// SetModel sets the "model" field.
func (u *GroupModelRateUpsertOne) SetModel(v string) *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupModelRateUpsertOne) UpdateModel() *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateModel()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *GroupModelRateUpsertOne) SetRateMultiplier(v float64) *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *GroupModelRateUpsertOne) AddRateMultiplier(v float64) *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *GroupModelRateUpsertOne) UpdateRateMultiplier() *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRateUpsertOne) SetUpdatedAt(v time.Time) *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRateUpsertOne) UpdateUpdatedAt() *GroupModelRateUpsertOne {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GroupModelRateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupModelRateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupModelRateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupModelRateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupModelRateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupModelRateCreateBulk is the builder for creating many GroupModelRate entities in bulk.
type GroupModelRateCreateBulk struct {
	config
	err      error
	builders []*GroupModelRateCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupModelRate entities in the database.
func (_c *GroupModelRateCreateBulk) Save(ctx context.Context) ([]*GroupModelRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupModelRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupModelRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupModelRateCreateBulk) SaveX(ctx context.Context) []*GroupModelRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupModelRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupModelRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupModelRate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupModelRateUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupModelRateCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupModelRateUpsertBulk {
	_c.conflict = opts
	return &GroupModelRateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupModelRateCreateBulk) OnConflictColumns(columns ...string) *GroupModelRateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupModelRateUpsertBulk{
		create: _c,
	}
}

// GroupModelRateUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupModelRate nodes.
type GroupModelRateUpsertBulk struct {
	create *GroupModelRateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupModelRateUpsertBulk) UpdateNewValues() *GroupModelRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupmodelrate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupModelRate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupModelRateUpsertBulk) Ignore() *GroupModelRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupModelRateUpsertBulk) DoNothing() *GroupModelRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupModelRateCreateBulk.OnConflict
// documentation for more info.
func (u *GroupModelRateUpsertBulk) Update(set func(*GroupModelRateUpsert)) *GroupModelRateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupModelRateUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupModelRateUpsertBulk) SetGroupID(v int64) *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupModelRateUpsertBulk) UpdateGroupID() *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateGroupID()
	})
}

// SetModel sets the "model" field.
func (u *GroupModelRateUpsertBulk) SetModel(v string) *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *GroupModelRateUpsertBulk) UpdateModel() *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateModel()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *GroupModelRateUpsertBulk) SetRateMultiplier(v float64) *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *GroupModelRateUpsertBulk) AddRateMultiplier(v float64) *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *GroupModelRateUpsertBulk) UpdateRateMultiplier() *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GroupModelRateUpsertBulk) SetUpdatedAt(v time.Time) *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GroupModelRateUpsertBulk) UpdateUpdatedAt() *GroupModelRateUpsertBulk {
	return u.Update(func(s *GroupModelRateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GroupModelRateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupModelRateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupModelRateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupModelRateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
